homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.story3, name='story3'),
    path('story32/', views.story32, name='story32'),
    path('story33/', views.story33, name='story33'),
    path('story34/', views.story34, name='story34'),

    # dilanjutkan ...
]

lab5/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.schedule, name='schedule'),
    path('create/', views.schedule_create, name='schedule_create'),
    path('delete/<int:id>/', views.schedule_delete, name='schedule_delete'),
    # dilanjutkan ...
]

story4responsive/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('lab5/', include(('lab5.urls', 'lab5'), namespace='lab5')),

]

homepage/models.py
from django.db import models

# Create your models here.
# from django.db import models
# from django.utils import timezone
# from datetime import datetime, date

# class Person(models.Model):
#      hari = models.CharField(max_length=30)
#     tanggal = models.DateTimeField(default=datetime.now)
     
#     phone_number = models.CharField(max_length=17)
#     id_line = models.CharField(max_length=6)
    

lab5/models.py
# Create your models here.
from django.db import models
from django.utils import timezone
from datetime import datetime, date

KEGEG = (
        ('happy', 'Menyenangkan'),
        ('normal', 'Biasa aja'),
        ('bored', 'Membosankan'),
    )

class Kegiatan(models.Model):
    hari = models.CharField(max_length=10)
    tanggal = models.DateField()
    jam = models.TimeField()
    namaKegiatan = models.CharField(max_length=30)
    tempat = models.CharField(max_length=30)
    kategori = models.CharField(max_length=1, choices=KEGEG)

lab5/forms.py
from django import  forms
from .models import Kegiatan

FAVORITE_COLORS_CHOICES = [
    ('blue', 'Blue'),
    ('green', 'Green'),
    ('black', 'Black'),
]

class FormJadwal(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = ['hari', 'tanggal', 'jam', 'namaKegiatan', 'kategori']
        widgets = {
            'tanggal': forms.DateInput(attrs={'type': 'date'}),
            'jam': forms.TimeInput(attrs={'type': 'time'})}
            
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })




# class Message_Form(forms.Form):
#     hari = models.CharField(max_length=10)
#     tanggal = models.DateField()
#     jam = models.TimeField()
#     namaKegiatan = models.CharField(max_length=30)
#     tempat = models.CharField(max_length=30)
#     kategori = models.CharField(max_length=30)

homepage/views.py
from django.shortcuts import render

# Create your views here.


def story3(request):
    return render(request, 'story3.html')

def story32(request):
    return render(request, 'story32.html')

def story33(request):
    return render(request, 'story33.html')

def story34(request):
    return render(request, 'story34.html')

lab5/views.py
from django.shortcuts import render, redirect
from .models import Kegiatan
from . import forms

def schedule(request):
    schedules = Kegiatan.objects.all().order_by('tanggal')
    return render(request, 'schedule.html', {'schedules': schedules})

def schedule_create(request):
    if request.method == 'POST':
        form = forms.FormJadwal(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lab5:schedule')

    else:
        form = forms.FormJadwal()
    return render(request, 'schedule_create.html', {'form': form})

def schedule_delete(request,id):
    if request.method == 'POST':
        Kegiatan.objects.filter(id=id).delete()
        return redirect('lab5:schedule')
    else :
        return httpresponse("/Get not load")

homepage/templates/story3.html
<!DOCTYPE html>
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet"  href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <script
    src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>
    <title>My web</title>
</head>
<body>
        <!-- <div class="sidenav">
                <a href="story3.html">Profile</a>
                <a href="story32.html">Experiences</a>
                <a href="story33.html">Contact</a>
                <a href="story34.html">Thanks</a>
              </div> -->
              <div class="topnav">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                  <a class="navbar-brand" href="{% url 'homepage:story3' %}">Profile</a>
                  <button
                    class="navbar-toggler"
                    type="button"
                    data-toggle="collapse"
                    data-target="#navbarText"
                    aria-controls="navbarText"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                  >
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav mr-auto">
                      <li class="nav-item active">
                        <a class="nav-link"   href="{% url 'homepage:story32' %}" 
                          >Experiences <span class="sr-only">(current)</span></a
                        >
                      </li>
                      <li class="nav-item active">
                        <a class="nav-link"  href="{% url 'homepage:story33' %}"
                          >Contact <span class="sr-only">(current)</span></a
                        >
                      </li>
                      <li class="nav-item active">
                        <a class="nav-link" href="{% url 'homepage:story34' %}"
                          >Thanks <span class="sr-only">(current)</span></a
                        >
                      </li>
                      <li class="nav-item active">
                        <a class="nav-link" href="{% url 'lab5:schedule_create' %}"
                          >Create Schedule <span class="sr-only">(current)</span></a
                        >
                      </li>
                      <li class="nav-item active">
                        <a class="nav-link" href="{% url 'lab5:schedule' %}"
                          >See Schedule <span class="sr-only">(current)</span></a
                        >
                      </li>
                    </ul>
                  </div>
                </nav>
              </div>
    <div class="row">
        <div class="col-6 ">
            <div class="face">
            <div class="potoprofil" >
                <img src="{% static 'images/potoprofil.jpg' %}" >
            </div>
            </div>
    </div>
        <div class="col-6 tulisan">
          <h1 style="font-size:4vw;">Muhammad </h1>
          <h1 style="font-size:4vw;" id="nama">Ramy Azhar</h1>
                <p>A Professional Programmer.</p>
            </div>
      </div>
      
    
</div>

</body>
</html>

homepage/templates/story32.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script
    src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>
    <meta charset="UTF-8">
  <title>My web</title>
  <!-- <style>
  body {
    background-image:%static ('potobg.jpg')%;
    background-size: cover;

}</style> -->
</head>
<body>
  <div class="semua">
      <!-- <div class="sidenav">
          <a href="story3.html">Profile</a>
          <a href="story32.html">Experiences</a>
          <a href="story33.html">Contact</a>
          <a href="story34.html">Thanks</a>
        </div> -->
        <div class="topnav">
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'homepage:story3' %}">Profile</a>
            <button
              class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbarText"
              aria-controls="navbarText"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link"   href="{% url 'homepage:story32' %}" 
                    >Experiences <span class="sr-only">(current)</span></a
                  >
                </li>
                <li class="nav-item active">
                  <a class="nav-link"  href="{% url 'homepage:story33' %}"
                    >Contact <span class="sr-only">(current)</span></a
                  >
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'homepage:story34' %}"
                    >Thanks <span class="sr-only">(current)</span></a
                  >
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'lab5:schedule_create' %}"
                    >Create Schedule <span class="sr-only">(current)</span></a
                  >
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'lab5:schedule' %}"
                    >See Schedule <span class="sr-only">(current)</span></a
                  >
                </li>
              </ul>
            </div>
          </nav>
        </div>
  <div class="container">
    <div class="row">
      <div class="col-2">
        <div class="fotoatas">
          <img src="{% static 'images/potoprofil.jpg' %}">
        </div>
      </div>
        <div class="col-10 my-3">
          <div class="mt-3">
              <b><p class="my-0">Muhammad</p>
                <p class="my-0" >Ramy Azhar</p></b>
          </div>
        </div>
    </div>
    <div class="row">
      <div class="col-6 " id="c51">
        <div class="rectangle1">
          <div class="tulisankotak">
            <h1 style="font-size:4vw;" id="exp"> Experiences </h1>
            <br>
            <div id="exp1">
              <p>2018-now
                <br> Software engineer at Grab</p>
              <p>2017-2016
                <br> Software engineer at Gojek</p>
              <p>2016-2017
                <br> UI/UX at Shopee </p>
              <p>2014-2016
                <br> Product Manager at Tokopedia</p>
                <br>
            </div>
          </div>
        </div>
      </div>
      <div class="col-6" id="c52">
        <div class="rectangle2">
          <div class="tulisankotak1">
            <h1 style="font-size:4vw;" id="sai"> Skill and Interest </h1>
            <br>
            <div  id="exp1">
              <p>Programming
                </p>
            
                <br>
              <p>UI/UX
                </p>
                <br>
              <p>Business Intelligence
                </p>
                <br>
                <p>Product Manager
                </p>
                <br>
                <br>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
  </div>
</body>

</html>

homepage/templates/story33.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <meta charset="UTF-8" />
    <title>My web</title>
  </head>
  <body>
    <!-- <div class="sidenav">
      <a href="story3.html">Profile</a>
      <a href="story32.html">Experiences</a>
      <a href="story33.html">Contact</a>
      <a href="story34.html">Thanks</a>
    </div> -->
    <div class="topnav">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'homepage:story3' %}">Profile</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarText"
          aria-controls="navbarText"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'homepage:story32' %}"
                >Experiences <span class="sr-only">(current)</span></a
              >
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'homepage:story33' %}"
                >Contact <span class="sr-only">(current)</span></a
              >
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'homepage:story34' %}"
                >Thanks <span class="sr-only">(current)</span></a
              >
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'lab5:schedule_create' %}"
                >Create Schedule <span class="sr-only">(current)</span></a
              >
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'lab5:schedule' %}"
                >See Schedule <span class="sr-only">(current)</span></a
              >
            </li>
          </ul>
        </div>
      </nav>
    </div>
    <div class="container">
      <div class="row" id="row3">
        <div class="col-6">
          <div class="fotokiri">
            <img src="{% static 'images/potokontak.jpg' %}" />
          </div>
        </div>
        <div class="col-6" id="row4">
          <h1 id="contactme">
            <b><i>Contact Me</i></b>
          </h1>
          <div class="kontak">
            <p><b>500 Terry Francois St.</b></p>
            <p><b>San Francisco, CA 94158</b></p>
            <p id="emil"><b>ramy@grab.com</b></p>
            <p><b>Tel: 123-456-7890</b></p>
          </div>
          <div class="row">
            <div class="col-4">
              <a href="https://www.facebook.com">
                <img
                  style="width: 100px;"
                  clas="img-responsive"
                  src="{% static 'images/fb.svg' %}"
                  alt="facebook"
                />
              </a>
            </div>
            <div class="col-4">
              <a href="https://www.twitter.com">
                <img
                  style="width: 100px;"
                  clas="img-responsive"
                  src="{% static 'images/tw.png' %}"
                  alt="twitter"
                  id="tw"
                />
              </a>
            </div>
            <div>
              <a href="https://www.instagram.com">
                <img
                  style="width: 100px;"
                  clas="img-responsive"
                  src="{% static 'images/ig.png' %}"
                  alt="Instagram"
                  id="igl"
                />
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

homepage/templates/story34.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <script
    src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>
    <meta charset="UTF-8" />
    <title>My web</title>
  </head>
  <body>
      <!-- <div class="sidenav">
          <a href="story3.html">Profile</a>
          <a href="story32.html">Experiences</a>
          <a href="story33.html">Contact</a>
          <a href="story34.html">Thanks</a>
        </div> -->
        <div class="topnav">
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'homepage:story3' %}">Profile</a>
            <button
              class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbarText"
              aria-controls="navbarText"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link"   href="{% url 'homepage:story32' %}" 
                    >Experiences <span class="sr-only">(current)</span></a
                  >
                </li>
                <li class="nav-item active">
                  <a class="nav-link"  href="{% url 'homepage:story33' %}"
                    >Contact <span class="sr-only">(current)</span></a
                  >
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'homepage:story34' %}"
                    >Thanks <span class="sr-only">(current)</span></a
                  >
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'lab5:schedule_create' %}"
                    >Create Schedule <span class="sr-only">(current)</span></a
                  >
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'lab5:schedule' %}"
                    >See Schedule <span class="sr-only">(current)</span></a
                  >
                </li>
              </ul>
            </div>
          </nav>
        </div>
      <div class="container text-center">
          <img src="{% static 'images/ty.png' %}" class="tyu-img" alt="thank you">
          <h1 id="upty">FOR VISITING MY WEBSITE</h1>
      </div>
      <div class="container">
        <div class="oll text-center">
    <div class="row" >
        <div class="tyu">
    </div>
    </div>
    <div class="row" id="oll2">
    </div>
    </div>
    
  </body>
</div>
</html>

lab5/templates/schedule.html
<!DOCTYPE html>
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <meta charset="UTF-8" />
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <title>My web</title>
  </head>
  <body>
    <!-- <div class="sidenav">
                <a href="story3.html">Profile</a>
                <a href="story32.html">Experiences</a>
                <a href="story33.html">Contact</a>
                <a href="story34.html">Thanks</a>
              </div> -->
    <div class="topnav">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'homepage:story3' %}">Profile</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarText"
          aria-controls="navbarText"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'homepage:story32' %}"
                >Experiences <span class="sr-only">(current)</span></a
              >
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'homepage:story33' %}"
                >Contact <span class="sr-only">(current)</span></a
              >
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'homepage:story34' %}"
                >Thanks <span class="sr-only">(current)</span></a
              >
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'lab5:schedule_create' %}"
                >Create Schedule <span class="sr-only">(current)</span></a
              >
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'lab5:schedule' %}"
                >See Schedule <span class="sr-only">(current)</span></a
              >
            </li>
          </ul>
        </div>
      </nav>
    </div>
    <h1>SCHEDULE</h1>
    <div class="article">
      <a href="{% url 'lab5:schedule' %}"></a>
      <div class="article">
        <div class="row">
          {% for schedule in schedules %}
          <div class="col-sm-4 text-center">
            <h2>{{ schedule.hari }}</h2>
            <p>{{ schedule.tanggal }}</p>
            <p>{{ schedule.jam }}</p>
            <p>{{ schedule.namaKegiatan }}</p>
            <p>{{ schedule.kategori }}</p>
            <div class="form-group">
              <form action="/lab5/delete/{{ schedule.id }}/" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-secondary btn-lg btn-sm">
                  Clear
                </button>
              </form>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="col-md-12">
      <div class="form-group">
        <a href="{% url 'lab5:schedule_create' %}"
          ><button type="button" class="btn btn-secondary btn-lg btn-sm">
            Create
          </button></a
        >
      </div>
    </div>
  </body>
</html>